/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * FoodTrip API
 * Complete API documentation for FoodTrip restaurant management system
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

// ============================================================================
// CONSTANTS & UTILITIES
// ============================================================================

const UUID = zod.string().uuid();
const DateString = zod.string();
const NullableDate = zod.string().nullable();
const Email = zod.string().email();
const Phone = zod.string().nullable();
const ImageId = zod.string().uuid().nullable();

// Pagination meta
export const PaginationMeta = zod.object({
  page: zod.number(),
  limit: zod.number(),
  totalItems: zod.number(),
  totalPages: zod.number(),
  previousPage: zod.number().nullable(),
  nextPage: zod.number().nullable(),
});

// Generic response wrapper
export const ResponseListWrapper = <T extends zod.ZodTypeAny>(dataSchema: T) =>
  zod.object({
    success: zod.boolean(),
    statusCode: zod.number(),
    message: zod.string(),
    data: dataSchema.optional(),
    meta: PaginationMeta.optional(),
    error: zod.string().optional(),
  });

export const ResponseWrapper = <T extends zod.ZodTypeAny>(dataSchema: T) =>
  zod.object({
    success: zod.boolean(),
    statusCode: zod.number(),
    message: zod.string(),
    data: dataSchema.optional(),
    error: zod.string().optional(),
  });

// ============================================================================
// REUSABLE ENTITY SCHEMAS
// ============================================================================

// Category (used in multiple places)
export const CategorySchema = zod.object({
  id: UUID,
  slug: zod.string(),
  name: zod.string(),
  description: zod.string().nullish(),
  createdAt: DateString,
  updatedAt: DateString,
  deletedAt: NullableDate,
});

// Restaurant (base fields)
export const RestaurantBaseSchema = zod.object({
  id: UUID,
  name: zod.string(),
  description: zod.string().nullable(),
  address: zod.string(),
  phone: Phone,
  email: Email.nullable(),
  imageId: ImageId,
  isAvailable: zod.boolean(),
  version: zod.number().min(0),
  createdAt: DateString,
  updatedAt: DateString,
  deletedAt: NullableDate,
});

// Dish (base fields)
export const DishBaseSchema = zod.object({
  id: UUID,
  restaurantId: UUID,
  categoryId: UUID,
  slug: zod.string(),
  name: zod.string(),
  description: zod.string().nullable(),
  price: zod.number().min(0),
  imageId: ImageId,
  stock: zod.number().min(0),
  isAvailable: zod.boolean(),
  isFeatured: zod.boolean(),
  version: zod.number().min(0),
  createdAt: DateString,
  updatedAt: DateString,
  deletedAt: NullableDate,
});

// Cart Item (with nested dish)
export const CartItemSchema = zod.object({
  id: UUID,
  cartId: UUID,
  dishId: UUID,
  quantity: zod.number().gt(0),
  price: zod.number().min(0),
  notes: zod.string().optional(),
  createdAt: DateString,
  updatedAt: DateString,
  dish: DishBaseSchema,
});

// Cart
export const CartSchema = zod.object({
  id: UUID,
  userId: UUID,
  restaurantId: UUID,
  createdAt: DateString,
  updatedAt: DateString,
  cartItems: zod.array(CartItemSchema),
});

// Order Item
export const OrderItemBaseSchema = zod.object({
  id: UUID,
  dishId: UUID,
  dishName: zod.string(),
  dishPrice: zod.number().min(0),
  quantity: zod.number().gt(0),
  subtotal: zod.number().min(0),
  notes: zod.string().optional(),
  createdAt: DateString,
});

// Order (base)
export const OrderBaseSchema = zod.object({
  id: UUID,
  orderNo: zod.string(),
  userId: UUID,
  restaurantId: UUID,
  subtotal: zod.number().min(0),
  deliveryFee: zod.number().min(0),
  tax: zod.number().min(0),
  total: zod.number().min(0),
  status: zod.enum([
    'PENDING',
    'CONFIRMED',
    'PREPARING',
    'DELIVERING',
    'COMPLETED',
    'CANCELLED',
  ]),
  paymentStatus: zod.enum(['UNPAID', 'PAID', 'FAILED', 'REFUNDED']),
  paymentMethod: zod.enum(['CASH', 'TRANSFER', 'EWALLET', 'QRIS']).optional(),
  customerName: zod.string(),
  customerPhone: zod.string(),
  deliveryAddress: zod.string(),
  notes: zod.string().optional(),
  orderedAt: DateString,
  confirmedAt: NullableDate,
  deliveredAt: NullableDate,
  completedAt: NullableDate,
  createdAt: DateString,
  updatedAt: DateString,
  deletedAt: NullableDate,
  orderItems: zod.array(OrderItemBaseSchema),
});

// User (for /me and admin)
export const UserSchema = zod.object({
  id: UUID,
  roleName: zod.string(),
  fullName: zod.string(),
  email: Email,
  phone: Phone,
  isActive: zod.boolean(),
  lastLoginAt: NullableDate,
  createdAt: DateString,
  updatedAt: DateString,
  deletedAt: NullableDate,
});

// Admin user with restaurants
export const AdminUserSchema = UserSchema.extend({
  roleId: UUID,
  restaurants: zod
    .array(zod.object({ restaurantId: UUID, restaurantRole: zod.string() }))
    .optional(),
});

// Upload file schema
export const UploadSchema = zod.object({
  id: UUID,
  originalName: zod.string(),
  filename: zod.string(),
  mimeType: zod.string(),
  type: zod.enum([
    'avatar',
    'restaurant_logo',
    'restaurant_banner',
    'dish_image',
  ]),
  folder: zod.string(),
  path: zod.string(),
  size: zod.number().min(0),
  uploadedById: UUID.nullable(),
  createdAt: DateString,
  updatedAt: DateString,
});

// ============================================================================
// PUBLIC ENDPOINTS
// ============================================================================

export const GetHealthResponse = ResponseWrapper(zod.unknown().nullish());

// Auth login
export const postApiAuthLoginBodyBodyPasswordMin = 8;
export const PostApiAuthLoginBody = zod.object({
  body: zod.object({
    email: Email,
    password: zod.string().min(8),
  }),
});
export const PostApiAuthLoginResponse = ResponseWrapper(
  zod
    .object({
      accessToken: zod.string().describe('JWT access token'),
      tokenType: zod.enum(['Bearer']),
      expiresIn: zod.string().describe('Token expiration interval'),
    })
    .optional()
);

// Auth register
export const postApiAuthRegisterBodyBodyPasswordMin = 8;
export const postApiAuthRegisterBodyBodyFullNameMin = 2;
export const postApiAuthRegisterBodyBodyPhoneMin = 10;
export const postApiAuthRegisterBodyBodyPhoneMax = 15;
export const PostApiAuthRegisterBody = zod.object({
  body: zod.object({
    email: Email,
    password: zod.string().min(8),
    fullName: zod.string().min(2),
    phone: zod.string().min(10).max(15),
  }),
});

export const GetApiAuthMeResponse = ResponseWrapper(UserSchema.optional());

// Restaurants (public)
export const GetApiRestaurantsQueryParams = zod.object({
  search: zod.string().optional(),
  page: zod.string().optional(),
  limit: zod.string().optional(),
  sortBy: zod.enum(['name', 'status', 'createdAt']).optional(),
  sortOrder: zod.enum(['asc', 'desc']).optional(),
});
export const GetApiRestaurantsResponse = ResponseWrapper(
  zod.array(RestaurantBaseSchema).optional()
);

export const GetApiRestaurantsRestaurantIdParams = zod.object({
  restaurantId: UUID,
});
export const GetApiRestaurantsRestaurantIdResponse = ResponseWrapper(
  RestaurantBaseSchema.optional()
);

// Dishes (public)
export const GetApiDishesQueryParams = zod.object({
  page: zod.string(),
  limit: zod.string(),
  search: zod.string().optional(),
  sortBy: zod.enum(['name', 'price', 'createdAt']).optional(),
  sortOrder: zod.enum(['asc', 'desc']).optional(),
});
export const GetApiDishesResponse = ResponseWrapper(
  zod.array(DishBaseSchema).optional()
);

export const GetApiDishesDishIdParams = zod.object({ dishId: UUID });
export const GetApiDishesDishIdResponse = ResponseWrapper(
  DishBaseSchema.optional()
);

// Categories (public)
export const GetApiCategoriesResponse = ResponseWrapper(
  zod.array(CategorySchema).optional()
);
export const GetApiCategoriesCategoryIdParams = zod.object({
  categoryId: UUID,
});
export const GetApiCategoriesCategoryIdResponse = ResponseWrapper(
  CategorySchema.optional()
);

// My Carts
export const GetApiMyCartsResponse = ResponseWrapper(
  zod.array(CartSchema).optional()
);

export const PostApiAddCartBody = zod.object({
  restaurantId: UUID,
  items: zod
    .array(
      zod.object({
        dishId: UUID,
        quantity: zod.number().gt(0),
        price: zod.number().min(0).optional(),
        notes: zod.string().optional(),
      })
    )
    .min(1),
});

export const PatchApiCartItemsItemIdParams = zod.object({ itemId: UUID });
export const PatchApiCartItemsItemIdResponse = ResponseWrapper(
  CartSchema.optional()
);

export const DeleteApiCartItemsItemIdParams = zod.object({ itemId: UUID });
export const DeleteApiCartItemsItemIdResponse = ResponseWrapper(
  zod.unknown().nullish()
);

// My Orders
export const GetApiMyOrdersResponse = ResponseWrapper(
  zod.array(OrderBaseSchema).optional()
);

export const GetApiOrdersOrderIdParams = zod.object({ orderId: UUID });
export const GetApiOrdersOrderIdResponse = ResponseWrapper(
  OrderBaseSchema.optional()
);

export const PostApiOrdersBody = zod.object({
  restaurantId: UUID,
  paymentMethod: zod.enum(['CASH', 'TRANSFER', 'EWALLET', 'QRIS']).optional(),
  customerName: zod.string().min(1),
  customerPhone: zod.string().min(1),
  deliveryAddress: zod.string().min(1),
  notes: zod.string().optional(),
});
export const PostApiOrdersResponse = ResponseWrapper(
  OrderBaseSchema.optional()
);

export const PatchApiOrdersOrderIdStatusParams = zod.object({ orderId: UUID });
export const PatchApiOrdersOrderIdStatusBody = zod.object({
  status: zod.enum([
    'PENDING',
    'CONFIRMED',
    'PREPARING',
    'DELIVERING',
    'COMPLETED',
    'CANCELLED',
  ]),
});
export const PatchApiOrdersOrderIdStatusResponse = ResponseWrapper(
  OrderBaseSchema.optional()
);

// ============================================================================
// ADMIN ENDPOINTS
// ============================================================================

export const GetApiAdminUsersResponse = ResponseWrapper(
  zod.array(AdminUserSchema).optional()
);
export const GetApiAdminUsersIdParams = zod.object({ id: UUID });
export const GetApiAdminUsersIdResponse = ResponseWrapper(
  AdminUserSchema.optional()
);

// Admin Categories
export const GetApiAdminCategoriesResponse = ResponseWrapper(
  zod.array(CategorySchema).optional()
);
export const PostApiAdminCategoriesBody = zod.object({
  slug: zod.string(),
  name: zod.string(),
  description: zod.string().nullable(),
});
export const GetApiAdminCategoriesCategoryIdParams = zod.object({
  categoryId: UUID,
});
export const GetApiAdminCategoriesCategoryIdResponse = ResponseWrapper(
  CategorySchema.optional()
);
export const PatchApiAdminCategoriesCategoryIdParams = zod.object({
  categoryId: UUID,
});
export const PatchApiAdminCategoriesCategoryIdBody = zod.object({
  slug: zod.string().optional(),
  name: zod.string().optional(),
  description: zod.string().nullish(),
});
export const PatchApiAdminCategoriesCategoryIdResponse = ResponseWrapper(
  CategorySchema.optional()
);
export const DeleteApiAdminCategoriesCategoryIdParams = zod.object({
  categoryId: UUID,
});
export const DeleteApiAdminCategoriesCategoryIdResponse = ResponseWrapper(
  zod.unknown().nullish()
);

// Admin Carts
export const GetApiAdminCartsResponse = ResponseWrapper(
  zod.array(CartSchema).optional()
);
export const PostApiAdminCartsBody = zod.object({
  userId: UUID,
  restaurantId: UUID,
  items: zod
    .array(
      zod.object({
        dishId: UUID,
        quantity: zod.number().gt(0),
        price: zod.number().min(0).optional(),
        notes: zod.string().optional(),
      })
    )
    .min(1),
});
export const PatchApiAdminCartsItemsItemIdParams = zod.object({ itemId: UUID });
export const PatchApiAdminCartsItemsItemIdBody = zod.object({
  quantity: zod.number().gt(0).optional(),
  notes: zod.string().optional(),
});
export const PatchApiAdminCartsItemsItemIdResponse = ResponseWrapper(
  CartSchema.optional()
);
export const DeleteApiAdminCartsItemsItemIdParams = zod.object({
  itemId: UUID,
});
export const DeleteApiAdminCartsItemsItemIdResponse = ResponseWrapper(
  zod.unknown().nullish()
);

// Admin Orders
export const GetApiAdminOrdersResponse = ResponseWrapper(
  zod.array(OrderBaseSchema).optional()
);
export const PostApiAdminOrdersBody = PostApiOrdersBody; // sama
export const PostApiAdminOrdersResponse = ResponseWrapper(
  OrderBaseSchema.optional()
);
export const GetApiAdminOrdersOrderIdParams = zod.object({ orderId: UUID });
export const GetApiAdminOrdersOrderIdResponse = ResponseWrapper(
  OrderBaseSchema.optional()
);
export const PatchApiAdminOrdersOrderIdStatusParams = zod.object({
  orderId: UUID,
});
export const PatchApiAdminOrdersOrderIdStatusBody =
  PatchApiOrdersOrderIdStatusBody;
export const PatchApiAdminOrdersOrderIdStatusResponse = ResponseWrapper(
  OrderBaseSchema.optional()
);
export const PatchApiAdminOrdersOrderIdPaymentStatusParams = zod.object({
  orderId: UUID,
});
export const PatchApiAdminOrdersOrderIdPaymentStatusBody = zod.object({
  paymentStatus: zod.enum(['UNPAID', 'PAID', 'FAILED', 'REFUNDED']),
});
export const PatchApiAdminOrdersOrderIdPaymentStatusResponse = ResponseWrapper(
  OrderBaseSchema.optional()
);

// Admin Dishes
export const GetApiAdminDishesQueryParams = GetApiDishesQueryParams;
export const GetApiAdminDishesResponse = ResponseWrapper(
  zod.array(DishBaseSchema).optional()
);

export const postApiAdminDishesBodyPriceMin = 0;
export const postApiAdminDishesBodyStockDefault = 0;
export const postApiAdminDishesBodyStockMin = 0;
export const postApiAdminDishesBodyIsAvailableDefault = true;
export const postApiAdminDishesBodyIsFeaturedDefault = false;
export const PostApiAdminDishesBody = zod.object({
  restaurantId: UUID,
  categoryId: UUID,
  slug: zod.string(),
  name: zod.string(),
  description: zod.string().nullable(),
  price: zod.number().min(0),
  imageId: ImageId,
  stock: zod.number().min(0).default(0),
  isAvailable: zod.boolean().default(true),
  isFeatured: zod.boolean().default(false),
});

export const GetApiAdminDishesDishIdParams = zod.object({ dishId: UUID });
export const GetApiAdminDishesDishIdResponse = ResponseWrapper(
  DishBaseSchema.optional()
);

export const PatchApiAdminDishesDishIdParams = zod.object({ dishId: UUID });
export const PatchApiAdminDishesDishIdBody = zod.object({
  restaurantId: UUID.optional(),
  categoryId: UUID.optional(),
  slug: zod.string().optional(),
  name: zod.string().optional(),
  description: zod.string().nullish(),
  price: zod.number().min(0).optional(),
  imageId: ImageId.nullish(),
  stock: zod.number().min(0).default(0),
  isAvailable: zod.boolean().default(true),
  isFeatured: zod.boolean().default(false),
});
export const PatchApiAdminDishesDishIdResponse = ResponseWrapper(
  DishBaseSchema.optional()
);

export const DeleteApiAdminDishesDishIdParams = zod.object({ dishId: UUID });
export const DeleteApiAdminDishesDishIdResponse = ResponseWrapper(
  zod.unknown().nullish()
);

// Admin Restaurants
export const GetApiAdminRestaurantsResponse = ResponseWrapper(
  zod.array(RestaurantBaseSchema).optional()
);

// Constants for restaurant creation/update
// const restaurantNameConstraints = { min: 3, max: 150 };
// const restaurantSlugConstraints = { min: 3, max: 150, regex: /^[a-z0-9-]+$/ };
// const restaurantDescriptionMax = 2000;
// const restaurantPhoneMax = 30;
// const restaurantEmailMax = 150;
// const restaurantAddressMin = 5;
// const restaurantCityMax = 100;
// const restaurantProvinceMax = 100;
// const restaurantPostalCodeMax = 20;
// const restaurantLatitudeRange = { min: -90, max: 90 };
// const restaurantLongitudeRange = { min: -180, max: 180 };
// const restaurantRejectedReasonMax = 1000;

export const PostApiAdminRestaurantsBody = zod.object({
  name: zod.string().min(3).max(150),
  slug: zod
    .string()
    .min(3)
    .max(150)
    .regex(/^[a-z0-9-]+$/),
  description: zod.string().max(2000).nullish(),
  phone: zod.string().max(30).optional(),
  email: Email.max(150).optional(),
  address: zod.string().min(5),
  city: zod.string().max(100).optional(),
  province: zod.string().max(100).optional(),
  postalCode: zod.string().max(20).optional(),
  latitude: zod.number().min(-90).max(90).nullish(),
  longitude: zod.number().min(-180).max(180).nullish(),
  logoId: UUID.nullish(),
  bannerId: UUID.nullish(),
  status: zod
    .enum(['PENDING', 'APPROVED', 'ACTIVE', 'SUSPENDED', 'REJECTED'])
    .optional(),
  isOpen: zod.boolean().optional(),
  openTime: zod.string().nullish(),
  closeTime: zod.string().nullish(),
  rejectedReason: zod.string().max(1000).optional(),
});

export const GetApiAdminRestaurantsRestaurantIdParams = zod.object({
  restaurantId: UUID,
});
export const GetApiAdminRestaurantsRestaurantIdResponse = ResponseWrapper(
  RestaurantBaseSchema.optional()
);

export const PatchApiAdminRestaurantsRestaurantIdParams = zod.object({
  restaurantId: UUID,
});
export const PatchApiAdminRestaurantsRestaurantIdBody =
  PostApiAdminRestaurantsBody.partial();
export const PatchApiAdminRestaurantsRestaurantIdResponse = ResponseWrapper(
  RestaurantBaseSchema.optional()
);

// Admin Uploads
export const PostApiAdminUploadsBody = zod.object({
  file: zod.unknown(),
  type: zod.string(),
});
export const PostApiAdminUploadsResponse = ResponseWrapper(
  UploadSchema.optional()
);

export const GetApiAdminUploadsResponse = ResponseWrapper(
  zod.array(UploadSchema).optional()
);

export const GetApiAdminUploadsIdParams = zod.object({ id: UUID });
export const GetApiAdminUploadsIdResponse = ResponseWrapper(
  UploadSchema.optional()
);

export const DeleteApiAdminUploadsIdParams = zod.object({ id: UUID });
export const DeleteApiAdminUploadsIdResponse = ResponseWrapper(
  zod.unknown().nullish()
);
